version: '2'
services:
  mysql:
    container_name: dockernet-mysql-56
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: user
      MYSQL_PASSWORD: 
    volumes:
      - mysqldata:/var/lib/mysql
networks:
  default:
    external:
      name: dockernet
volumes:
  mysqldata:
    driver: "local"