version: '2'
services:
  phpmyadmin:
    container_name: dockernet-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "6033:80"
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
networks:
  default:
    external:
      name: dockernet